fix2

diff --git a/.github/workflows/playground_examples_reusable.yml b/.github/workflows/playground_examples_reusable.yml
--- a/.github/workflows/playground_examples_reusable.yml
+++ b/.github/workflows/playground_examples_reusable.yml
@@ -60,23 +60,27 @@ jobs:
       - name: install deps
         run: pip install -r requirements.txt
         working-directory: playground/infrastructure
-      - id: check_has_example
-        name: has Examples
+      - name: get Difference
+        id: check_file_changed
         run: |
-          # don't quit on errors, check unbound vars, and show commands
-          set +e -ux
-          
+          set -xeu
           # define the base ref
           BASE_REF=$GITHUB_BASE_REF
           if [ -z "$BASE_REF" ] || [ "$BASE_REF" == "master" ]; then
             BASE_REF=origin/master
           fi
-           
+          DIFF=$(git diff --name-only $BASE_REF $GITHUB_SHA)
+          echo "::set-output name=example_diff::$DIFF"
+      - id: check_has_example
+        name: has Examples
+        run: |
+          # don't quit on errors, check unbound vars, and show commands
+          set +e -ux
           python3 checker.py \
             --verbose \
             --sdk SDK_${SDK^^} \
             --whitelist ${{ inputs.whitelist }} \
-            --paths $(git diff --name-only $BASE_REF $GITHUB_SHA)
+            --paths "${{ steps.check_file_changed.outputs.example_diff }}"
           if [ $? -eq 0 ]; then
             echo "::set-output name=example_has_changed::True"
           else
