renamse

diff --git a/.github/workflows/playground_examples_ci_reusable.yml b/.github/workflows/playground_examples_ci_reusable.yml
--- a/.github/workflows/playground_examples_ci_reusable.yml
+++ b/.github/workflows/playground_examples_ci_reusable.yml
@@ -13,15 +13,21 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-name: Playground Examples CI for a given SDK and origin
+name: Playground Examples CI/CD for a given SDK and origin
 
 on:
   workflow_call:
     inputs:
+      step:
+        type: string
+        required: true
       sdk:
         type: string
         required: true
       subdirs:
+        type: string
+        required: true
+      allowlist:
         type: string
         required: true
       origin:
@@ -30,13 +36,66 @@ on:
 env:
   BEAM_VERSION: 2.40.0
 jobs:
-  ci:
-    name: CI ${{ inputs.sdk }} ${{ inputs.origin }}
+  check_has_examples:
+    name: pre-check
+    runs-on: ubuntu-latest
+    outputs:
+      example_has_changed: ${{ steps.check_has_example.outputs.example_has_changed }}
+    env:
+      ORIGIN: ${{ inputs.origin }}
+      SDK: ${{ inputs.sdk }}
+      STEP: ${{ inputs.step }}
+      SUBDIRS: ${{ inputs.subdirs }}
+    steps:
+      - name: Check out the repo
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - uses: actions/setup-python@v4
+        with:
+          python-version: '3.8'
+      - name: install deps
+        run: pip install -r requirements.txt
+        working-directory: playground/infrastructure
+      - name: get Difference
+        id: check_file_changed
+        run: |
+          set -xeu
+          # define the base ref
+          BASE_REF=$GITHUB_BASE_REF
+          if [ -z "$BASE_REF" ] || [ "$BASE_REF" == "master" ]; then
+            BASE_REF=origin/master
+          fi
+          DIFF=$(git diff --name-only $BASE_REF $GITHUB_SHA | tr '\n' ' ')
+          echo "::set-output name=example_diff::$DIFF"
+      - id: check_has_example
+        name: has Examples
+        run: |
+          # don't quit on errors, check unbound vars, and show commands
+          set +e -ux
+          python3 checker.py \
+            --verbose \
+            --sdk SDK_${SDK^^} \
+            --allowlist ${{ inputs.allowlist }} \
+            --paths ${{ steps.check_file_changed.outputs.example_diff }}
+          if [ $? -eq 0 ]; then
+            echo "::set-output name=example_has_changed::True"
+          else
+            echo "::set-output name=example_has_changed::False"
+          fi
+        working-directory: playground/infrastructure
+        env:
+          BEAM_ROOT_DIR: "../.."
+
+  ci_cd:
+    name: ${{ inputs.step }} ${{ inputs.sdk }} ${{ inputs.origin }}
+    needs: [ check_has_examples ]
+    if: needs.check_has_examples.outputs.example_has_changed == 'True'
     runs-on: ubuntu-latest
     env:
       ORIGIN: ${{ inputs.origin }}
       SDK: ${{ inputs.sdk }}
-      STEP: CI
+      STEP: ${{ inputs.step }}
       SUBDIRS: ${{ inputs.subdirs }}
     steps:
       - name: Check out the repo
